export const getSidebarTexts = (t) => ({
  appName: t("appName"),
  appSubTitle: t("appSubTitle"),
  dashboard: t("dashboard"),
  archive: t("archive"),
  hifziya: t("hifziya"),
  makzan: t("makzan"),
  profile: t("profile"),
  settings: t("settings"),
  users: t("users"),
  auditLogs: t("auditLogs"),
  userManagement: t("userManagement"),
  logout: t("logout"),
  notifications: t("notifications"),
  languagePashto: t("languagePashto"),
  languageDari: t("languageDari"),
  languageEnglish: t("languageEnglish"),
  user: t("user"),
});
