const getMinotMakatibTexts = (t) => ({
  // Page
  title: t("page.title"),
  newRecord: t("page.newRecord"),
  recordTypeForDirection: t("page.recordTypeForDirection"),
  viewIncoming: t("viewIncoming"),
  viewOutgoing: t("viewOutgoing"),

  // Table Headers
  headerNo: t("table.headers.no"),
  headerOrg: t("table.headers.org"),
  headerSubject: t("table.headers.subject"),
  headerLetterNumber: t("table.headers.letterNumber"),
  headercartonNumber: t("table.headers.cartonNumber"),
  headeryear: t("table.headers.year"),
  headerSummary: t("table.headers.summary"),
  headerDescription: t("table.headers.description"),
  headerDirection: t("table.headers.direction"),
  headerActions: t("table.headers.actions"),

  // Filter
  recordType: t("filter.recordType"),
  all: t("filter.all"),
  incomming: t("filter.incomming"),
  outgoing: t("filter.outgoing"),
  bookNumber: t("filter.bookNumber"),
  province: t("filter.province"),
  district: t("filter.district"),
  filter: t("filter"),
  search: t("search"),

  // Actions
  view: t("actions.view"),
  edit: t("actions.edit"),
  delete: t("actions.delete"),
  newWareda: t("actions.newWarada"),
  newSadera: t("actions.newSadera"),
  back: t("actions.back"),

  // Delete Dialog
  deleteTitle: t("deleteDialog.title"),
  deleteText: t("deleteDialog.text"),
  deleteCancel: t("deleteDialog.cancel"),
  deleteConfirm: t("deleteDialog.confirm"),
  deleteSuccess: t("deleteDialog.success"),
  deleteError: t("deleteDialog.error"),

  // Scanner
  scannerFolderPath: t("scanner.folderPath"),
  scannerFolderTitle: t("scanner.folderTitle"),
  scanButton: t("scanner.scanButton"),
  scanning: t("scanner.scanning"),
  loadFiles: t("scanner.loadFiles"),
  clickToScan: t("scanner.clickToScan"),
  filesAvailable: t("scanner.filesAvailable"),
  detectedFiles: t("scanner.detectedFiles"),
  noFiles: t("scanner.noFiles"),
  filesFound: t("scanner.filesFound"),
  scanError: t("scanner.scanError"),
  loadSuccess: t("scanner.loadSuccess"),
  loadError: t("scanner.loadError"),
  // Upload
  manualUpload: t("upload.manualUpload"),
  readyToUpload: t("upload.readyToUpload"),
  removeAll: t("upload.removeAll"),
  // Edit
  editTitle: t("edit.title"),
  uploadNew: t("edit.uploadNew"),
  newFiles: t("edit.newFiles"),
  existingFiles: t("edit.existingFiles"),
  newFilesList: t("edit.newFilesList"),
  allowedFormats: t("edit.allowedFormats"),
  maxSize: t("edit.maxSize"),
  replaceWarning: t("edit.replaceWarning"),
  editRecordType: t("edit.recordType"),
  editHifziya: t("edit.hifziya"),
  editMakhzan: t("edit.makhzan"),
  no: t("edit.no"),
  org: t("edit.org"),
  subject: t("edit.subject"),
  letterNumber: t("edit.letterNumber"),
  cartonNumber: t("edit.cartonNumber"),
  year: t("edit.year"),
  summary: t("edit.summary"),
  description: t("edit.description"),
  loading: t("edit.loading"),
  required: t("edit.required"),
  cancel: t("edit.cancel"),
  save: t("edit.save"),
  saving: t("edit.saving"),
  loadError: t("edit.loadError"),
  requiredFields: t("edit.requiredFields"),
  updateSuccess: t("edit.updateSuccess"),
  updateError: t("edit.updateError"),

  // View
  scanButtonInfo: t("view.scanButtonInfo"),
  scan: t("view.scan"),

  viewAddTitle: t("view.Addtitle"),
  viewTitle: t("view.title"),
  viewNumber: t("view.number"),
  viewOrganization: t("view.organization"),
  viewSubject: t("view.subject"),
  viewLetterNumber: t("view.letterNumber"),
  viewcartonNumber: t("view.cartonNumber"),
  headeryear: t("view.year"),
  viewSummary: t("view.summary"),
  viewDescription: t("view.description"),
  viewNoData: t("view.noData"),
  viewClose: t("view.close"),

  // ===== Cabinet =====
  cabinetAddress: t("cabinetAddress"),
  cabinet: t("cabinet"),
  cabinets: t("cabinets"),
  floor: t("floor"),
  floors: t("floors"),
  shelf: t("shelf"),
  shelves: t("shelves"),
  file: t("file"),
  files: t("files"),
  rowsPerPage: t("rowsPerPage"),
  of: t("of"),
});

export default getMinotMakatibTexts;
