export const getLoginTexts = (t) => ({
  welcomeBack: t("welcomeBack"),
  welcomeDescription: t("welcomeDescription"),
  signIn: t("signIn"),
  dontHaveAccount: t("dontHaveAccount"),
  getStarted: t("getStarted"),
  usernameLabel: t("usernameLabel"),
  usernamePlaceholder: t("usernamePlaceholder"),
  usernameRequired: t("usernameRequired"),
  passwordLabel: t("passwordLabel"),
  passwordPlaceholder: t("passwordPlaceholder"),
  passwordRequired: t("passwordRequired"),
  forgotPassword: t("forgotPassword"),
  signInButton: t("signInButton"),
  loading: t("loading"),
  verify2FADescription: t("verify2FADescription"),
  verify2FAButton: t("verify2FAButton"),
  codeRequired: t("codeRequired"),
  info: t("info"),
});
